lidofinance/community-staking-module

src/CSEarlyAdoption.sol
src/CSModule.sol
src/interfaces/ICSEarlyAdoption.sol
test/CSEarlyAdoption.t.sol

- Immutable vars in EA
- Remove unused state var in CSM

chore: Fix minor stuff detected by slither

---

test/CSModule.t.sol

To be used as an example for the possible future fuzz tests

chore: Add dumb fuzzing tests

---

src/lib/QueueLib.sol
test/QueueLib.t.sol
test/fork/invariant/Invariants.t.sol

Some commits are supplied with the explanation. Merge with rebase!

chore: Todos resolve

---

.github/workflows/regular.yml
src/CSAccounting.sol
src/abstract/CSBondCore.sol
src/abstract/CSBondCurve.sol

This PR includes possible minor improvements submitted as in-code todos.
Review stopped at line `CSAccounting:332`

CS Accounting Todos Part 1

---

.github/workflows/regular.yml
src/CSAccounting.sol
src/abstract/CSBondCore.sol
src/abstract/CSBondCurve.sol

This PR includes possible minor improvements submitted as in-code todos.
Review stopped at line `CSAccounting:332`

chore: CS Accounting Todos Part 1

---

src/lib/UnstructuredStorage.sol
test/CSAccounting.t.sol
test/CSModule.t.sol
test/OssifiableProxy.t.sol

chore: Missing test coverage

---

script/DeployHolesky.s.sol
test/fork/invariant/Invariants.t.sol

Testnet also has 2nd dev team admin

fix: invariants checks for admin role

---

src/CSFeeDistributor.sol
src/CSFeeOracle.sol
src/CSModule.sol
src/abstract/CSBondLock.sol
test/CSAccounting.t.sol
test/CSFeeDistributor.t.sol
test/CSModule.t.sol
test/fork/integration/RecoverTokens.t.sol

Merge with rebase to keep commits

Multiple audit fixes

---

test/fork/deployment/PostDeployment.t.sol

make sure merging it after testnet contracts are updated

chore: add missed assert for new parameter

---

.github/workflows/regular-holesky.yml
.github/workflows/regular-mainnet.yml

chore: Fix and extend regular tests

---

.env.sample
.github/workflows/regular-mainnet.yml
.github/workflows/test.yml
Justfile
fork.just
script/DeployBase.s.sol
script/DeployImplementationsBase.s.sol
script/DeployImplementationsHolesky.s.sol
script/DeployImplementationsMainnet.s.sol
script/fork-helpers/Common.sol
script/fork-helpers/SimulateVote.s.sol
script/utils/Json.sol
test/fork/deployment/InitialState.t.sol
test/fork/deployment/PostDeployment.t.sol
test/fork/deployment/Upgradability.sol
test/fork/integration/ClaimInTokens.t.sol
test/fork/integration/DepositInTokens.t.sol
test/fork/integration/GateSeal.t.sol
test/fork/integration/Penalty.t.sol
test/fork/integration/RecoverTokens.t.sol
test/fork/invariant/Invariants.t.sol
test/fork/voting/StakingRouter.t.sol
test/fork/voting/StatePostVote.t.sol
test/helpers/Fixtures.sol

mainnet launch https://github.com/lidofinance/community-staking-module/actions/runs/11661406745/job/32465647009

tests: run integration tests on the contracts after upgrade

---

script/DeployCSVerifierElectra.s.sol

https://github.com/eth-clients/holesky/commit/34d0a04577b36dcf5ba304a2ba8222c8f1f4e639

Electra slot

---

package.json
yarn.lock

elliptic alerts will be fixed when new version of openzeppelin/merkle-tree released

upd lint-staged deps

---

Justfile
test/fork/invariant/Invariants.t.sol
test/fork/voting/StakingRouter.t.sol
test/helpers/InvariantAsserts.sol

rework deposits tests to avoid deposits for unpredictable amount of keys
chore: add progress bar for some tests

tests: run invariants checks only on CI

---

script/fork-helpers/SimulateVote.s.sol
src/CSAccounting.sol
src/CSFeeDistributor.sol
src/CSModule.sol
src/interfaces/ICSAccounting.sol
src/interfaces/ICSFeeDistributor.sol
src/interfaces/ICSModule.sol
test/CSAccounting.t.sol
test/CSFeeDistributor.t.sol
test/CSFeeOracle.t.sol
test/CSModule.t.sol
test/fork/deployment/PostDeployment.t.sol

add corresponding view methods

feat: bump upgradeable contract versions

---

Justfile
README.md
script/DeployBase.s.sol
script/DeployCSVerifierElectra.s.sol
script/DeployLocalDevNet.s.sol

Local devnet

---

src/CSFeeOracle.sol
src/CSModule.sol
src/interfaces/ICSFeeOracle.sol
src/interfaces/ICSModule.sol
test/CSAccounting.t.sol
test/CSFeeDistributor.t.sol
test/CSFeeOracle.t.sol
test/CSModule.t.sol

- todos and minor changes after review round

Review round #1. fix: take into account withdrawn keys for the keys limit

---

script/DeployBase.s.sol
script/DeployHoodi.s.sol
script/DeployImplementationsBase.s.sol
script/DeployLocalDevNet.s.sol
script/DeployMainnet.s.sol
script/fork-helpers/SimulateVote.s.sol
test/fork/deployment/PostDeployment.t.sol

Rename existing EA to LegacyEA
Fix parameter names
Add tests

feat: Use new Node Operator Type for ICS

---

src/CSModule.sol
src/lib/NOAddresses.sol
test/CSModule.t.sol

This PR fixes several INFO findings discovered during Statemind security audit for CSM v2

chore: Fix several INFO findings by Statemind 

---

src/CSModule.sol
src/interfaces/ICSModule.sol

chore: Improve func docs

---

src/CSAccounting.sol
src/abstract/CSBondLock.sol
test/CSAccounting.t.sol

Fixes two INFO severity findings

chore: Audit fixes for Statemind findings

---

src/interfaces/ICSAccounting.sol

chore: Add minor natspec notes

---

.github/workflows/test.yml
script/DeployBase.s.sol
script/DeployHolesky.s.sol
script/DeployHoodi.s.sol
script/DeployImplementationsBase.s.sol
script/DeployLocalDevNet.s.sol
script/DeployMainnet.s.sol
script/fork-helpers/SimulateVote.s.sol
src/CSAccounting.sol
src/abstract/BondReserve.sol
src/interfaces/IBondReserve.sol
src/interfaces/ICSAccounting.sol
test/BondReserve.t.sol
test/CSAccounting.t.sol
test/fork/deployment/PostDeployment.t.sol
test/fork/integration/CreateAndDeposit.sol
test/fork/integration/misc/ProxyUpgrades.sol
test/helpers/InvariantAsserts.sol

Due to [CM v2 spec](https://hackmd.io/Y8_64-eKQiODGR1l5_Ux1A?view#Reserve-additional-bond)
⚠️ **NOTE**: There is no `ValMart` notification about any changes in the reserve.

feat: `BondReserve.sol`

---

ics-assessment/engagement/main.py

fix: high signal score calculation

---

src/CSModule.sol
src/CSStrikes.sol
test/CSModule.t.sol

This PR fixes 2 findings from the Statemind audit

audit: Statemind fixes 2
